"""Build a real PGA layout: wired op-amp + Rin + Rf poly resistors.

Topology (non-inverting amp):
  vinp → opamp + input
  vfb  → opamp − input
  Rf   from vout to vfb
  Rin  from vfb to vbcm (mid-rail)
  Gain = 1 + Rf/Rin

This first-pass uses fixed resistors. The programmable 0..40 dB
switched-R network is the next iteration — add 7 more resistor tap
points + NMOS pass-gate switches.
"""

import os
from pathlib import Path
import gdstk

# Reuse the wiring helpers from wire_opamp.py
import sys
sys.path.insert(0, str(Path(__file__).parent))
from wire_opamp import (
    L_METAL1, L_METAL2, L_VIA12, L_TEXT, L_PR_BNDRY,
    rect, lbl, metal2_wire, via_stack, build_wired_opamp,
)


def build_pga(workdir: Path) -> gdstk.Library:
    # First build the wired op-amp (returns the library it lives in)
    op_lib = build_wired_opamp(workdir)
    op_cell = op_lib.cells[-1]

    # Now build the PGA library
    pga_lib = gdstk.Library(name="PGA", unit=1e-6, precision=1e-9)

    # Import op-amp + its dependencies into pga_lib
    for c in [op_cell] + list(op_cell.dependencies(True)):
        if c.name not in [x.name for x in pga_lib.cells]:
            pga_lib.add(c)

    pga = pga_lib.new_cell("pga_real")

    # Place op-amp at (0,0)
    pga.add(gdstk.Reference(op_cell, origin=(0, 0)))

    # Import resistor PCells
    for rname, x_pos, y_pos in [("r_in", 130, 30),     # short resistor right of opamp
                                 ("r_fb", 130, 80)]:    # longer resistor above
        gds = workdir / f"{rname}.gds"
        if gds.exists():
            r_sub_lib = gdstk.read_gds(str(gds))
            r_sub = r_sub_lib.top_level()[0]
            for c in [r_sub] + list(r_sub.dependencies(True)):
                if c.name not in [x.name for x in pga_lib.cells]:
                    pga_lib.add(c)
            pga.add(gdstk.Reference(r_sub, origin=(x_pos, y_pos)))

    # Wiring on metal2:
    # vout (op-amp output, at right of op-amp ≈ x=82, y=120 — top of M6) → top of Rf
    metal2_wire(pga, 90, 130, 130, 130)            # horizontal
    metal2_wire(pga, 130, 130, 130, 100)           # down into Rf
    pga.add(lbl("vout_pga", 95, 135))

    # bottom of Rf → vfb (op-amp − input = M1.gate area, x≈0, y≈0 bottom of NMOS)
    metal2_wire(pga, 130, 80, 130, 50)             # down from Rf
    metal2_wire(pga, 0,   50, 130, 50)             # horizontal back to op-amp
    pga.add(lbl("vfb", 50, 55))

    # vfb → top of Rin
    metal2_wire(pga, 130, 50, 130, 40)             # short bridge

    # bottom of Rin → vbcm (mid-rail bias generated by Vref block)
    metal2_wire(pga, 130, 30, 160, 30)             # off to vbcm pad
    pga.add(lbl("vbcm", 160, 30))

    # Port labels
    pga.add(lbl("vinp",  -3, -55, L_TEXT))
    pga.add(lbl("vout", 175, 130, L_TEXT))

    # Outline for the PGA block
    pga.add(rect(-15, -65, 200, 220, L_PR_BNDRY))
    pga.add(lbl("PGA (Rin=1k, Rf=100k, gain=100x)", 90, -75, L_TEXT))

    return pga_lib


if __name__ == "__main__":
    workdir = Path(os.environ.get("AFE_WORKDIR", "."))
    lib = build_pga(workdir)
    out = workdir / "pga_real.gds"
    lib.write_gds(str(out))
    print(f"wrote {out} ({out.stat().st_size} B)")
